// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PolyglotNotebooks
{
    internal sealed partial class Vsix
    {
        public const string Id = "PolyglotNotebooks.52d750bb-4c45-43d1-bc22-a9d5fe2cdf91";
        public const string Name = "Polyglot Notebooks";
        public const string Description = @"Interactive notebook experience for Visual Studio. Execute C#, JavaScript, and SQL code in cells with rich output, IntelliSense, and cross-language variable sharing. Powered by .NET Interactive.";
        public const string Language = "en-US";
        public const string Version = "1.0.902";
        public const string Author = "Mads Kristensen";
        public const string Tags = "notebook;interactive;polyglot;csharp;javascript;sql;repl";
        public const bool IsPreview = false;
    }
}
