// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PolyglotNotebooks
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PolyglotNotebooksString = "7a8b905d-687d-4b8c-8842-85067272e3ab";
        public static Guid PolyglotNotebooks = new Guid(PolyglotNotebooksString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowVariableExplorer = 0x0105;
        public const int InsertCodeCellAbove = 0x0200;
        public const int InsertCodeCellBelow = 0x0201;
        public const int InsertMarkdownCellAbove = 0x0202;
        public const int InsertMarkdownCellBelow = 0x0203;
        public const int MoveCellUp = 0x0204;
        public const int MoveCellDown = 0x0205;
        public const int DeleteCell = 0x0206;
        public const int ToggleMarkdownEdit = 0x0207;
        public const int ClearCellOutput = 0x0208;
        public const int ChangeCellLanguage = 0x0209;
    }
}
